version:  2

conda:
  environment: docs/environment.yaml

python:
  version: 3.10

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false

# Optionally build your docs in additional formats such as PDF
formats:
  - pdf
